# Generated by Django 5.1.4 on 2024-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateField()),
            ],
            options={
                'db_table': 'absences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursGlobal',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cours', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cours_global',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mdp', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'etudiants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentsGlobaux',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('description_incident', models.TextField(default='Aucune description')),
                ('date_signalement', models.DateField()),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'incidents_globaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscriptionGlobale',
            fields=[
                ('id_inscription_globale', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inscriptions_globales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteGlobale',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_saisie', models.DateField()),
            ],
            options={
                'db_table': 'notes_globales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanningGlobal',
            fields=[
                ('id_planning', models.AutoField(primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=100)),
                ('horaire', models.TimeField()),
            ],
            options={
                'db_table': 'plannings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=255)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'professeurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalleGlobale',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('numero_salle', models.IntegerField()),
                ('statut', models.BooleanField(default=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'salles_globales',
                'managed': False,
            },
        ),
    ]
