# Generated by Django 5.1.4 on 2024-12-18 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursGlobal',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cours', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentsGlobaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=255)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalleGlobale',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('numero_salle', models.CharField(max_length=50)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateField()),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.coursglobal')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='NoteGlobale',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_saisie', models.DateField()),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.coursglobal')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='coursglobal',
            name='id_professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.professeur'),
        ),
        migrations.AddField(
            model_name='coursglobal',
            name='id_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.salleglobale'),
        ),
    ]
